[package]
name = "blue-build"
version = "0.4.1"
edition = "2021"
description = "A CLI tool built for creating Containerfile templates based on the Ublue Community Project"
repository = "https://gitlab.com/wunker-bunker/blue-build"
license = "Apache-2.0"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
askama = { version = "0.12.1", features = ["serde-json"] }
cfg-if = "1.0.0"
chrono = "0.4.31"
clap = { version = "4.4.4", features = ["derive"] }
clap-verbosity-flag = "2.1.1"
derive_builder = "0.12.0"
env_logger = "0.10.1"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
typed-builder = "0.18.0"
users = "0.11.0"

[features]
default = ["build"]
nightly = ["build"]
init = []
build = []

[dev-dependencies]
rusty-hook = "0.11.2"
