[package]
name = "ublue-rs"
version = "0.2.0"
edition = "2021"
description = "A CLI tool built for creating Containerfile templates based on the Ublue Community Project"
repository = "https://gitlab.com/wunker-bunker/ublue-cli"
license = "Apache-2.0"
categories = ["command-line-utilities"]
exclude = [".gitlab-ci.yml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
tera = "1.19.1"

[features]
default = []
nightly = ["init", "build"]
init = []
build = []
