name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git setup
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/cache@v4
        with:
          path: |
            target/
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
          key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}

      - uses: chainguard-dev/actions/setup-gitsign@main

      # Pulling rust toolchain & install linux dependencies
      - uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-release
        uses: taiki-e/install-action@v1
        with:
          tool: cargo-smart-release

      - name: Release
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo smart-release -ue
